on:
  pull_request:
  push:
    branches:
      - main

jobs:
  vale:
    name: vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
      - run: npm install -g mdx2vast

      - uses: errata-ai/vale-action@v2.1.1
        # with:
        #   fail_on_error: true

  internal-links:
    name: internal-links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
      - run: npm install -g mintlify

      - run: mintlify broken-links

  lychee:
    name: lychee
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore lychee cache
        uses: actions/cache@v4
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - uses: lycheeverse/lychee-action@v2
        with:
          fail: true
