on:
  - pull_request
  - push

jobs:
  vale:
    name: vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.1
        with:
          fail_on_error: true
